### ISSUE TITLE
generate failing on latest qemu trunk

### ISSUE THREAD

**Issue by shevek** [shevek/qemu-java#5]
They added a "struct" concept?

```
shevek@raven:~/java/qemu-java$ ./gradlew --daemon generate 
:qemu-qapi:compileGenerateJava UP-TO-DATE
:qemu-qapi:processGenerateResources UP-TO-DATE
:qemu-qapi:generateClasses UP-TO-DATE
:qemu-qapi:generate
Download https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.12/slf4j-simple-1.7.12.pom
Download https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.12/slf4j-simple-1.7.12.jar
Exception in thread "main" java.lang.IllegalArgumentException: Unknown JsonObject {"struct":"NameInfo","data":{"*name":"str"}}
        at org.anarres.qemu.qapi.generator.SchemaParser.parse(SchemaParser.java:94)
        at org.anarres.qemu.qapi.generator.Main.main(Main.java:43)
:qemu-qapi:generate FAILED
```

**Comment by shuowang1989** [comment]
Any plan to fix this? latest one seems to have "pragma" that's also not supported.

**Comment by shevek** [comment]
I'd love to have the time. I'll take a patch.

**Comment by djfroofy** [comment]
Bump https://github.com/shevek/qemu-java/pull/11
